---
version: 1.0.{build}.{branch}

matrix:
  fast_finish: true

# We always use a 64-bit machine.
platform:
  - x64

environment:

  matrix:

    - PYTHON: '3.8'

install:
  - echo "Filesystem root:"
  - dir C:\

build_script:
  - py -%PYTHON% %APPVEYOR_BUILD_FOLDER%\appveyor\env_info.py

test_script:
  - py -%PYTHON% %APPVEYOR_BUILD_FOLDER%\mingw_info.py
