env:
    global:
        - REPO_DIR=bezier
        - BUILD_COMMIT=9c2c7003d64242542f931088a8646c30cc4a2caa
        - BUILD_DEPENDS="numpy"
        - TEST_DEPENDS="--requirement bezier/scripts/osx/requirements.txt"
        - PLAT=x86_64
        - UNICODE_WIDTH=32

language: python
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
    - python: 3.5
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code ${REPO_DIR} ${BUILD_COMMIT}
    - build_wheel ${REPO_DIR} ${PLAT}

script:
    - install_run ${PLAT}

after_success:
    - find ${TRAVIS_BUILD_DIR}/wheelhouse/
    - virtualenv --python=python2.7 gsutil-env
    - gsutil-env/bin/pip install gsutil
    - gsutil-env/bin/gsutil cp ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl gs://${GCS_BUCKET}
