---
version: 1.0.{build}.{branch}

matrix:
  fast_finish: true

# We always use a 64-bit machine.
platform:
  - x64

environment:

  global:
    REPO_DIR: bezier
    PACKAGE_NAME: bezier
    BUILD_COMMIT: 56a275aac704f4b48166c390fbd044f5a98e3960
    BUILD_DEPENDS: "numpy"
    TEST_DEPENDS: "--requirement scripts\\requirements.txt"
    BEZIER_JOURNAL: "%APPVEYOR_BUILD_FOLDER%\\bezier\\journal.txt"
    BEZIER_WHEEL: "True"

    MINGW_32: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
    MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin

  matrix:

    # See: https://www.appveyor.com/docs/installed-software/#python

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  # Fetch submodules
  - git submodule update --init --recursive

  - cmd: echo "Filesystem root:"
  - dir C:\

  - echo "Installed SDKs:"
  - dir "C:/Program Files/Microsoft SDKs/Windows"

  # Prepend "current" Python to the PATH of this build.
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Append MinGW to the PATH of this build so ``gfortran`` is visible
  # to ``numpy.distutils``.
  - ps: |
      $PYTHON = $env:PYTHON
      If ($PYTHON.EndsWith("-x64")) {
          $MINGW = $env:MINGW_64
      } Else {
          $MINGW = $env:MINGW_32
      }
      $env:Path += ";$MINGW"

  # Check that we have the expected version and architecture for Python.
  - python env_info.py

  # Packaging requirements
  # Pin wheel to 0.26.0 to avoid Windows ABI tag for built wheel
  # For context: https://github.com/pypa/wheel/issues/161 and
  #              https://github.com/pypa/wheel/issues/171
  - python -m pip install --upgrade pip setuptools virtualenv
  - python -m pip install "wheel==0.26.0"

  # Install the build dependencies of the project.
  - python -m pip install --upgrade %BUILD_DEPENDS%

build_script:
  # build wheel:
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%

  - ..\build_wheel.cmd

  - ps: |
      # Upload artifact to Appveyor immediately after build
      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
      }

test_script:
  # Assumes `cd %REPO_DIR%` was called previously.
  - python -m virtualenv test-venv

  # Install test dependencies.
  - test-venv\Scripts\pip install %TEST_DEPENDS%

  # Install package from local built wheel.
  - test-venv\Scripts\pip install --no-index --find-links "%APPVEYOR_BUILD_FOLDER%\\wheelhouse" %PACKAGE_NAME%

  # Verify speedups are built.
  - test-venv\Scripts\python ..\check_speedup.py

  # Run unit and functional tests.
  - test-venv\Scripts\py.test tests\unit
  - test-venv\Scripts\py.test tests\functional

artifacts:
  - path: "bezier\\journal.txt"

on_failure:
  # Assumes `cd %REPO_DIR%` was called previously.
  - appveyor PushArtifact "journal.txt"
