environment:
  global:
    REPO_DIR: bezier
    PACKAGE_NAME: bezier
    BUILD_COMMIT: 430a0b666b7ef71d06a744fcf83860cddf23c524
    BUILD_DEPENDS: "numpy>=1.9.0"
    TEST_DEPENDS: "numpy>=1.9.0 pytest six scipy"
    BEZIER_JOURNAL: "C:\\projects\\bezier-wheels\\bezier\\journal.txt"

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C %APPVEYOR_BUILD_FOLDER%\\multibuild\\ci\\appveyor\\windows_sdk.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: true

install:
    # Fetch submodules
    - git submodule update --init --recursive

    - cmd: echo "Filesystem root:"
    - dir C:\

    - echo "Installed SDKs:"
    - dir "C:/Program Files/Microsoft SDKs/Windows"

    # Prepend "current" Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    # Prepend MinGW to the PATH of this build so ``gfortran`` is visible
    # to ``numpy.distutils``.
    - SET PATH=%MINGW%;%PATH%

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"
    - python -c "import os, sys; print(os.name); print(sys.platform); print(sys.version)"

    # Install requirements
    - python -m pip install --upgrade pip
    - pip install wheel

build_script:
    # Install build requirements
    - pip install --upgrade %BUILD_DEPENDS%

    # build wheel:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - "%CMD_IN_ENV% python setup.py bdist_wheel"

test_script:
    # Assumes `cd %REPO_DIR%` was called previously.
    - python -m virtualenv test-venv
    - test-venv\Scripts\pip install --upgrade --requirement ..\requirements.txt
    - test-venv\Scripts\pip install --upgrade wheel
    - test-venv\Scripts\pip install bezier --no-index --find-links dist
    - test-venv\Scripts\python -c "import bezier; print(bezier._HAS_HELPERS_SPEEDUP)"
    - test-venv\Scripts\py.test tests\unit
    - test-venv\Scripts\python -c "import bezier._curve_intersection_speedup as sp; print(sp)"
    - test-venv\Scripts\python -c "import bezier._curve_speedup as sp; print(sp)"
    - test-venv\Scripts\python -c "import bezier._helpers_speedup as sp; print(sp)"
    - test-venv\Scripts\python -c "import bezier._surface_speedup as sp; print(sp)"

artifacts:
    - path: "bezier\\journal.txt"
    - path: "%REPO_DIR%\\dist\\*"

on_failure:
    # Assumes `cd %REPO_DIR%` was called.
    # e.g. https://ci.appveyor.com/api/buildjobs/3a1mtmvgt92vdy9v/artifacts/journal.txt
    # from https://ci.appveyor.com/project/dhermes/bezier-wheels/build/1.0.21/job/3a1mtmvgt92vdy9v
    - appveyor PushArtifact "journal.txt"
    - 7z a wheels.zip "dist\*.whl"
    - appveyor PushArtifact wheels.zip
