environment:
  global:
    REPO_DIR: bezier
    PACKAGE_NAME: bezier
    BUILD_COMMIT: be44789367cf6dd319f128409bd55740fc1825ce
    BUILD_DEPENDS: "numpy>=1.9.0"
    TEST_DEPENDS: "numpy>=1.9.0 pytest six scipy"
    BEZIER_JOURNAL: "'C:\\projects\\bezier-wheels\\bezier\\journal.txt"

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C %APPVEYOR_BUILD_FOLDER%\\multibuild\\ci\\appveyor\\windows_sdk.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      MINGW: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32\\bin"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      MINGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: true

install:
    # Fetch submodules
    - git submodule update --init --recursive

    - cmd: echo "Filesystem root:"
    - dir C:\

    - echo "Installed SDKs:"
    - dir "C:/Program Files/Microsoft SDKs/Windows"

    # Prepend "current" Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    # Prepend MinGW to the PATH of this build
    - SET PATH=%MINGW%;%PATH%

    # Fix MSVC builds for 64-bit Python
    # See
    # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
    - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"
    - python -c "import os, sys; print(os.name); print(sys.platform)"

    # Install requirements
    - python -m pip install --upgrade pip
    - pip install wheel

    # Print some information about the Fortran compiler
    - python find_gfortran.py

build_script:
    # Install build requirements
    - pip install --upgrade %BUILD_DEPENDS%

    # build wheel:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - "%CMD_IN_ENV% python setup.py bdist_wheel"

test_script:
    # "%CMD_IN_ENV% python -c \"import bezier; print(bezier._HAS_SPEEDUP)\""
    - python -c "print('Hello')"

artifacts:
    - path: "%BEZIER_JOURNAL%"

on_failure:
    # Assumes `cd %REPO_DIR%` was called.
    - appveyor PushArtifact "journal.txt"
